install:
	./gradlew clean install
run-dist:
	./build/install/app/bin/app
build:
	./gradlew clean build
lint:
	./gradlew checkstyleMain
test:
	./gradlew test
report:
	./gradlew jacocoTestReport

.PHONY: build